language: ruby
before_install:
- gem install bundler
rvm:
- 2.5.1
- 2.4.4
- ruby-head
matrix:
  allow_failures:
  - rvm: ruby-head
  fast_finish: true
env:
  matrix:
  - VAGRANT_VERSION=v2.1.5
  global:
    secure: bs4ezY+1Wksy8hH3nymPJ3AL99mpXULVc/AIh16JetEYw1850QkX7r4gQukMlcyByKUhxucjDLid0Y+KDH5kGMM16QjrVQGhAnUQzMoLD2qPbAaxDCUqpCJtFEEQKYxJvFvEK8a5SQzAsTVG4sgABQ/MllsIIH0FjkWgFtH6050=
script: bundle exec rake test:unit
