language: ruby
before_install:
- gem update --system
- gem install bundler
rvm:
- ruby-head
- 2.5.1
- 2.4.4
matrix:
  allow_failures:
  - rvm: ruby-head
  fast_finish: true
env:
  matrix:
  - VAGRANT_VERSION=v2.1.5
script: bundle exec rake test:unit
